name: notificacion_job
description: "Notificar el resultat del test via email"
inputs:
  MAIL_USERNAME: 
    description: "Email del remitent del correu"
    required: true
  MAIL_PASSWORD:
    description: "Contrasenya del remitent del correu"
    required: true
  OAUTH_CLIENT_ID:
    description: "Client id de l'aplicació de google"
    required: true
  OAUTH_CLIENT_SECRET:
    description: "Client secret de l'aplicació de google"
    required: true
  OAUTH_REFRESH_TOKEN:  
    description: "Refresh token de l'aplicació de google"
    required: true
  linter_job:
    description: "Resultat linter job"
    required: true
  cypress_job: 
    description: "Resultat del cypress job"
    required: true
  badge_job:
    description: "Resultat del badge_job"
    required: true
  deploy_job:
    description: "Resultat del deploy_job"
    required: true
runs:
  using: "node12"
  main: "src/dist/index.js"