name: notificacion_job
description: "Notificar el resultat del test via email"
inputs:
  destinatari_email: 
    descrtiption: "Email del destinatari del correu"
    required: true
  remitent_email: 
    description: "Email del remitent del correu"
    required: true
  # remitent_password:
  #   description: "Contrasenya del remitent del correu"
  #   required: true
  client_id:
    description: "Client id de l'aplicaci贸 de google"
    required: true
  client_secret:
    description: "Client secret de l'aplicaci贸 de google"
    required: true
  refresh_token:  
    description: "Refresh token de l'aplicaci贸 de google"
    required: true
  # acces_token:
  #   description: "Acces token de l'aplicaci贸 de google"
  #   required: true  
  linter_job:
    description: "Resultat linter job"
    required: true
  cypress_job: 
    description: "Resultat del cypress job"
    required: true
  badge_job:
    description: "Resultat del badge_job"
    required: true
  deploy_job:
    description: "Resultat del deploy_job"
    required: true
runs:
  using: "node12"
  main: "src/dist/index.js"